#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards

yarn test && git add .   ||
(
    echo '❌👷🔨❌ Better Call your mentor... Because your test failed ❌👷🔨❌
            next test failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
